### ISSUE TITLE
FEATURE - [Allow to Combine Multiple Xero Companies]

### ISSUE THREAD

**Issue by tconticello** [fivetran/dbt_xero#15]
**Are you a Fivetran customer?** 
Fernando Tomas Conticello, Data Consultant, Ocula

**Is your feature request related to a problem? Please describe.**
I want to have a feature to allow run the packages (Xero and Xero_Source) for multiple companies using the fivetran xero connector. 
At the moment the package only allows to run one company.
**Describe the solution you'd like**
Solution is similar to https://blog.montrealanalytics.com/how-to-use-the-shopify-dbt-package-by-fivetran-with-multiple-shops-eb4cea326ee0

**Describe alternatives you've considered**
-Generate union base of companies
-Allow Xero_Sources to have pass through column variables
-Allow Xero to have pass through column variables
-Modify the queries of xero models to allow grouping by those  pass through column as well. There is a group by (7) in some Xero models that need to be modified to allow other columns coming from the pass through columns

**Additional context**

**Please indicate the level of urgency and business impact of this request** 
Important

**Are you interested in contributing to this package?** 
- [X ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented. 
- [ ] No, I'd prefer if someone else did this.  I don't have the time and/or don't know how to incorporate the changes necessary.

**Comment by fivetran-reneeli** [comment]
Hey @tconticello  @jazzy-r , we've updated the package to allow for multiple connectors. Please refer to the [release notes](https://github.com/fivetran/dbt_xero/releases/tag/v0.3.0) for more info! Let me know if you have questions and thanks for helping us make our packages more useful!
