### ISSUE TITLE
[Bug] Bank Transaction table missing

### ISSUE THREAD

**Issue by santi95** [fivetran/dbt_xero#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

One of our 3 Xero instances doesn't have the bank_transaction table and most models are skipped because of this.

### Expected behavior

If the table doesn't exist, users should be able to not include it in the models being ran through a variable, just like the credit_note

### dbt Project configurations

We just use the standard configuration for this package.

models:
  xero:
    +tags: 'default_transformation_xero'
    +schema: "dataset"
  xero_source:
    +tags: 'default_transformation_xero'
    +schema: "dataset"

### Package versions

  - package: fivetran/xero
    version: 0.4.0

### What database are you using dbt with?

bigquery

### dbt Version

version: 1.0.1

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by santi95** [comment]
Hey @fivetran-joemarkiewicz thank you for the quick reply.

I already coded the changes, my only question would be about repo synchronization, because this change requires both changes in the dbt_xero and the dbt_xero_source. How would it be better to submit both PRs? I was thinking on linking the dbt_xero_source changes on the main one, would this be ok?

Creating the PR soon!

**Comment by fivetran-joemarkiewicz** [comment]
@santi95 this is great thanks so much for opening this PR 💯! 

The way you have done this is perfect with the two PRs and the reference in this issue. I will review these for you tomorrow! The only thing I will ask off the bat is:
- [ ] Make sure to update the README to include this new variable for both the source/modeling packages. 
- [ ] Increase the index of the package version in the [dbt_project.yml](https://github.com/fivetran/dbt_xero_source/blob/main/dbt_project.yml#L2) files 
- [ ] Add your contribution to the CHANGELOG.md files for both the source/modeling packages

Those are what I was able to see at a cursory glance. Everything else I will review in more detail tomorrow 😄

**Comment by santi95** [comment]
@fivetran-joemarkiewicz Just uploaded the requested changes!
Thanks for everything

**Comment by fivetran-joemarkiewicz** [comment]
Hey @santi95 thanks again so much for your contributions! 🙌 

I just cut the release for the dbt_xero `v0.4.1` and you should see the release be live on the dbt hub at the top of the hour. Thanks again for your collaboration and please feel free to open another issue or feature request in the future if you encounter any issues or would like more flexibility to the package. 😄
