### ISSUE TITLE
[Bug] Test Failure in dbt xero package

### ISSUE THREAD

**Issue by ElliottWilson** [fivetran/dbt_xero#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I am getting an error on this test:
`dbt_utils_unique_combination_of_columns_xero__balance_sheet_report_source_relation__date_month__account_name (models/xero.yml)`

Adding account_id to the test seems to fix it.

### Relevant error log or model output

```shell
Failure in test dbt_utils_unique_combination_of_columns_xero__balance_sheet_report_source_relation__date_month__account_name (models/xero.yml)
```

### Expected behavior

The test should pass for the test Failure in test  dbt_utils_unique_combination_of_columns 
 on table xero__balance_sheet_report `(dbt_utils_unique_combination_of_columns_xero__balance_sheet_report_source_relation__date_month__account_name (models/xero.yml))`

### dbt Project configurations

N/A

### Package versions

- package: fivetran/xero
    version: [">=0.4.0", "<0.5.0"]

### What database are you using dbt with?

snowflake

### dbt Version

1.1.2

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @ElliottWilson thanks so much for opening this issue! 

Would you mind sharing the details of the records that where the test failed? Were these scenarios where different account ids had the same name? If that is the case then I think your proposal for adding `account_id` to test uniqueness is the right call. If not, I would like to explore the test failure some more.

Additionally, I see you are open to creating a PR 🎉. If the above looks appropriate and adding `account_id` is the correct fix, then I encourage you to open a PR and our team can review and work to integrate your contribution into the package. Let me know if you have any questions!

**Comment by ElliottWilson** [comment]
Hello @fivetran-joemarkiewicz ! Thanks for the speedy response. Here are and example of the rows that cause the test to fail: 
![image](https://user-images.githubusercontent.com/32582638/186270456-8ed69ae1-0782-45f4-b30f-091ed77095eb.png)

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for sending that over @ElliottWilson! Hmmm that is interesting that we are seeing two records of `Retained Earnings`. I am getting the suspicious that something else may be going wrong. 🤔 

It looks like we have some logic [here](https://github.com/fivetran/dbt_xero/blob/b7554b52c45760aeef93bdfea799088552f35676/models/xero__balance_sheet_report.sql#L31-L35) in the package that generates `Retained Earnings` as the account name when the following is true: 
```sql
ledger.journal_date <= {{ dbt_utils.dateadd('year', -1, 'year_end.current_year_end_date') }}
```
This looks like our package generating the retained earnings record; however, you already have a Retained Earnings account defined. Does the total for the first record (the one with the `null` account_id) look accurate? If so, we may just need to add a unique account_id for this created record.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @ElliottWilson I just wanted to post back to see if the other account_id total amount looks accurate?

Our team will be happy to add code to ensure this test does not fail, but wanted to confirm that the values were still accurate before moving forward.

**Comment by fivetran-avinash** [comment]
Hey @ElliottWilson! Just wanted to dig deeper here before we deploy a test fix--do the amounts for these accounts look accurate?

We're concerned that we could be overengineering a fix for a proper test failure, since there are two records of Retained Earnings showing. Any investigation results you can provide on your end would be great!

**Comment by fivetran-joemarkiewicz** [comment]
Closing this issue as it has gone stale. Please feel free to reopen if the issue still persists.
