### ISSUE TITLE
Add more cols to xero__balance_sheet_report / xero__invoice_line_items / xero__profit_and_loss_report views.

### ISSUE THREAD

**Issue by wasifaleemdd** [fivetran/dbt_xero#4]
#### xero__balance_sheet_report
* account_id
* account_type

#### xero__invoice_line_items 
* account_id

#### xero__profit_and_loss_report
* account_class

**Comment by fivetran-kristin** [comment]
thanks for the request @wasifaleemdd !

**Comment by fivetran-kristin** [comment]
These fields have been added and will be part of our first release.

This package should be available for download through dbt's hub shortly!
